[package]
name = "metapod"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
ash = "0.38.0"
ash-window = "0.13.0"
cgmath = "0.18.0"
egui = "0.31.0"
env_logger = "0.11.6"
log = "0.4.25"
png = "0.17.16"
thiserror = "2.0.11"
winit = "0.30.9"
